### ISSUE TITLE
customActionTrigger() throwing Cross-Origin Request error

### ISSUE THREAD

**Issue by joancipria** [JiteshGaikwad/ChatbotWidget#29]
Hi! First of all, I want to thank you so much for this awesome project. My bot should start the conversation so I've enabled `customActionTrigger()` from `script.js` and changed the `action_name` const with my custom action. Then, when I try ChatbotWidget it throws the following cross-origin problem:

`Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at http://localhost:5055/webhook/. (Reason: CORS header ‘Access-Control-Allow-Origin’ missing).`

`Error from bot end:  error`

I've used `rasa run -m models --enable-api --cors "*" --debug` to run the server following the instructions so I don't know why it doesn't allow the request since I use the `--cors` flag

**Comment by JiteshGaikwad** [comment]
@joancipria  you need to start the action server using the below command
> rasa run actions --cors "*"

**Comment by joancipria** [comment]
Oh, I forgot the actions server! Thank you so much, it worked!
